/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type CarouselField = {
  _type: "carouselField";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
};

export type DynamicIntro = {
  _type: "dynamicIntro";
  eyebrow?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
    listItem?: "number" | "bullet" | "check";
    markDefs?: Array<{
      customLink?: CustomUrl;
      _type: "customLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type ImageCarousel = {
  _type: "imageCarousel";
  eyebrow?: string;
  title?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
    listItem?: "number" | "bullet" | "check";
    markDefs?: Array<{
      customLink?: CustomUrl;
      _type: "customLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  buttons?: Array<{
    _key: string;
  } & Button>;
  carousel?: Array<{
    _key: string;
  } & CarouselField>;
};

export type SplitForm = {
  _type: "splitForm";
  title?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
    listItem?: "number" | "bullet" | "check";
    markDefs?: Array<{
      customLink?: CustomUrl;
      _type: "customLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  form?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "form";
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Cta = {
  _type: "cta";
  title?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
    listItem?: "number" | "bullet" | "check";
    markDefs?: Array<{
      customLink?: CustomUrl;
      _type: "customLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type Hero = {
  _type: "hero";
  title?: string;
  isTitleH1?: boolean;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
    listItem?: "number" | "bullet" | "check";
    markDefs?: Array<{
      customLink?: CustomUrl;
      _type: "customLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type FormFields = {
  _type: "formFields";
  fields?: Array<{
    _key: string;
  } & FormField>;
};

export type FormField = {
  _type: "formField";
  required?: boolean;
  fieldName?: string;
  placeholder?: string;
  fieldId?: string;
  inputType?: "text" | "email" | "phone" | "textArea" | "file" | "checkbox";
  checkboxFields?: {
    checkboxTitle?: string;
    items?: Array<{
      required?: boolean;
      label?: string;
      description?: string;
      value?: string;
      _key: string;
    }>;
  };
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "inline";
  listItem?: "number" | "bullet" | "check";
  markDefs?: Array<{
    customLink?: CustomUrl;
    _type: "customLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type NavDropdownColumn = {
  _type: "navDropdownColumn";
  title?: string;
  columns?: Array<{
    _key: string;
  } & NavLinkColumn>;
};

export type NavLinkColumn = {
  _type: "navLinkColumn";
  title?: string;
  icon?: IconPicker;
  description?: string;
  url?: CustomUrl;
};

export type Button = {
  _type: "button";
  variant?: "default" | "secondary" | "outline" | "link";
  icon?: IconPicker;
  buttonText?: string;
  url?: CustomUrl;
};

export type NavLink = {
  _type: "navLink";
  title?: string;
  url?: CustomUrl;
};

export type PageBuilder = Array<({
  _key: string;
} & Hero) | ({
  _key: string;
} & Cta) | ({
  _key: string;
} & SplitForm) | ({
  _key: string;
} & ImageCarousel) | ({
  _key: string;
} & DynamicIntro)>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  links?: Array<{
    _key: string;
  } & NavLink>;
};

export type Logo = {
  _id: string;
  _type: "logo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  links?: Array<({
    _key: string;
  } & NavLink) | ({
    _key: string;
  } & NavDropdownColumn)>;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type MarketingModal = {
  _id: string;
  _type: "marketingModal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  isActive?: boolean;
  title?: string;
  description?: string;
  form?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "form";
  };
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: Array<{
    _key: string;
  } & InternationalizedArrayReferenceValue>;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mainPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "form";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndex";
  };
};

export type BlogIndex = {
  _id: string;
  _type: "blogIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  language?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoNoIndex?: boolean;
  seoHideFromLists?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  cardTitle?: string;
  cardDescription?: string;
  cardImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Form = {
  _id: string;
  _type: "form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  title?: string;
  formId?: string;
  language?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
  buttonText?: string;
};

export type MainPage = {
  _id: string;
  _type: "mainPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  language?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoNoIndex?: boolean;
  seoHideFromLists?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  cardTitle?: string;
  cardDescription?: string;
  cardImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  richText?: RichText;
  language?: string;
  pageBuilder?: PageBuilder;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoNoIndex?: boolean;
  seoHideFromLists?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  cardTitle?: string;
  cardDescription?: string;
  cardImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  language?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoNoIndex?: boolean;
  seoHideFromLists?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  cardTitle?: string;
  cardDescription?: string;
  cardImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type CustomUrl = {
  _type: "customUrl";
  type?: "internal" | "external";
  openInNewTab?: boolean;
  external?: string;
  href?: string;
  internal?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blogIndex";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "blog";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mainPage";
  };
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message?: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | ({
    _key: string;
  } & SanityAssistInstructionFieldRef) | ({
    _key: string;
  } & SanityAssistInstructionContext) | ({
    _key: string;
  } & SanityAssistInstructionUserInput)>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    path?: string;
    _type: "sanity.assist.output.field";
    _key: string;
  } | {
    type?: string;
    _type: "sanity.assist.output.type";
    _key: string;
  }>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};
export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/app/sitemap.ts
// Variable: sitemapQuery
// Query: *[_type in $types && defined(slug.current) && seoNoIndex != true ]{  "slug":slug.current,  _updatedAt,  _type,  _id}
export type SitemapQueryResult = Array<{
  slug: null;
  _updatedAt: string;
  _type: "assist.instruction.context";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "footer";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "form";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "logo";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "marketingModal";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "media.tag";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "navbar";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "sanity.fileAsset";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "sanity.imageAsset";
  _id: string;
} | {
  slug: null;
  _updatedAt: string;
  _type: "translation.metadata";
  _id: string;
}>;

// Source: ../web/src/lib/sanity/query.ts
// Variable: getAllSlugPagePathsQuery
// Query: *[_type == "page" && defined(slug.current) && !seoNoIndex]{  "slug":slug.current,  "locale":language}
export type GetAllSlugPagePathsQueryResult = Array<{
  slug: string | null;
  locale: string | null;
}>;
// Variable: getAllMainPageTranslationsQuery
// Query: *[_type == "mainPage"].language
export type GetAllMainPageTranslationsQueryResult = Array<string | null>;
// Variable: getBlogIndexDataQuery
// Query: {    "seo":*[_type == "blogIndex" && select(($locale == 'en-GB' || $locale == '' ) =>   (!defined(language) || language == 'en-GB'), language == $locale => language == $locale)][0]{        ...,    },    "blogs":*[_type == "blog" && select(($locale == 'en-GB' || $locale == '' ) =>   (!defined(language) || language == 'en-GB'), language == $locale => language == $locale)]{      _id,      "title":coalesce(cardTitle,title),"description":coalesce(cardDescription,description),"image":coalesce(cardImage,image),      "slug":slug.current    }}
export type GetBlogIndexDataQueryResult = {
  seo: {
    _id: string;
    _type: "blogIndex";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
    language?: string;
    seoTitle?: string;
    seoDescription?: string;
    seoImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    seoNoIndex?: boolean;
    seoHideFromLists?: boolean;
    ogTitle?: string;
    ogDescription?: string;
    cardTitle?: string;
    cardDescription?: string;
    cardImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
  blogs: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    slug: string | null;
  }>;
};
// Variable: getAllBlogIndexTranslationsQuery
// Query: *[_type == "blogIndex"].language
export type GetAllBlogIndexTranslationsQueryResult = Array<string | null>;
// Variable: getAllBlogsPathsQuery
// Query: *[_type == "blog" && defined(slug.current) && !seoNoIndex]{  "slug":slug.current,  "locale":language}
export type GetAllBlogsPathsQueryResult = Array<{
  slug: string | null;
  locale: string | null;
}>;
// Variable: getFooterDataQuery
// Query: *[_type == "footer"][0]{    _id,    title,    defined(links)=>{  links[]{    ...,    title,    _type,    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }},    defined(columns)=>{  columns[]{    ...,    title,    description,    defined(icon)=>{  icon{    svg  }},    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }}  }}  }},    "logo":*[_type == "logo"][0].image.asset->url}
export type GetFooterDataQueryResult = {
  _id: string;
  title: string | null;
  links: Array<{
    _key: string;
    title: string | null;
    _type: "navLink";
    url: {
      openInNewTab: boolean | null;
      href: string | null;
    } | null;
    columns: null;
  }> | null;
  logo: string | null;
} | null;
// Variable: getNavbarDataQuery
// Query: *[_type == "navbar"][0]{    _id,    title,    defined(links)=>{  links[]{    ...,    title,    _type,    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }},    defined(columns)=>{  columns[]{    ...,    title,    description,    defined(icon)=>{  icon{    svg  }},    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }}  }}  }},    defined(buttons)=>{  buttons[]{    ...,    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }},    defined(icon)=>{  icon{    svg  }}  }},    "logo":*[_type == "logo"][0].image.asset->url  }  
export type GetNavbarDataQueryResult = {
  _id: string;
  title: string | null;
  links: Array<{
    _key: string;
    title: string | null;
    _type: "navDropdownColumn";
    url: null;
    columns: Array<{
      _key: string;
      title: string | null;
      description: string | null;
      icon: {
        svg: string | null;
      } | null;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    title: string | null;
    _type: "navLink";
    url: {
      openInNewTab: boolean | null;
      href: string | null;
    } | null;
    columns: null;
  }> | null;
  buttons: Array<{
    _key: string;
    url: {
      openInNewTab: boolean | null;
      href: string | null;
    } | null;
    icon: {
      svg: string | null;
    } | null;
  }> | null;
  logo: string | null;
} | null;
// Variable: getBlogPageDataQuery
// Query: *[_type == "blog" && slug.current == $slug && select(($locale == 'en-GB' || $locale == '' ) =>   (!defined(language) || language == 'en-GB'), language == $locale => language == $locale)][0]{    ...,    defined(richText)=>{  richText[]{    ...,     defined(markDefs)=>{  markDefs[]{    ...,    defined(customLink)=>{  customLink{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }}     }}     }}  }  
export type GetBlogPageDataQueryResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  richText: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    markDefs: null;
  } | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
    listItem?: "bullet" | "check" | "number";
    markDefs: Array<{
      customLink: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      _type: "customLink";
    }> | null;
    level?: number;
    _type: "block";
  }> | null;
  language?: string;
  pageBuilder?: PageBuilder;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoNoIndex?: boolean;
  seoHideFromLists?: boolean;
  ogTitle?: string;
  ogDescription?: string;
  cardTitle?: string;
  cardDescription?: string;
  cardImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
} | null;
// Variable: getMainPageDataQuery
// Query: *[_type == "mainPage" && select(($locale == 'en-GB' || $locale == '' ) =>   (!defined(language) || language == 'en-GB'), language == $locale => language == $locale)][0]{  _id,  _type,  title,  description,  defined(pageBuilder)=>{  pageBuilder[]{    ...,    _type,    defined(buttons)=>{  buttons[]{    ...,    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }},    defined(icon)=>{  icon{    svg  }}  }},    defined(richText)=>{  richText[]{    ...,     defined(markDefs)=>{  markDefs[]{    ...,    defined(customLink)=>{  customLink{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }}     }}     }},    defined(form)=>{  form->{    ...,  }}  }}}
export type GetMainPageDataQueryResult = {
  _id: string;
  _type: "mainPage";
  title: string | null;
  description: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "cta";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "dynamicIntro";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "hero";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "imageCarousel";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "splitForm";
    buttons: null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: {
      _id: string;
      _type: "form";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label?: string;
      title?: string;
      formId?: string;
      language?: string;
      fields?: Array<{
        _key: string;
      } & FormField>;
      buttonText?: string;
    } | null;
  }> | null;
} | null;
// Variable: getSlugPageDataQuery
// Query: *[_type == "page" && slug.current == $slug ][0]{    _id,    _type,    title,    content,    "slug":slug.current,    defined(pageBuilder)=>{  pageBuilder[]{    ...,    _type,    defined(buttons)=>{  buttons[]{    ...,    defined(url)=>{  url{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }},    defined(icon)=>{  icon{    svg  }}  }},    defined(richText)=>{  richText[]{    ...,     defined(markDefs)=>{  markDefs[]{    ...,    defined(customLink)=>{  customLink{    openInNewTab,    "href": select(type == "internal"=>internal->slug.current, type == "external" => external,"#"),  }}     }}     }},    defined(form)=>{  form->{    ...,  }}  }}    }
export type GetSlugPageDataQueryResult = {
  _id: string;
  _type: "page";
  title: string | null;
  content: null;
  slug: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "cta";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "dynamicIntro";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "hero";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "imageCarousel";
    buttons: Array<{
      _key: string;
      url: {
        openInNewTab: boolean | null;
        href: string | null;
      } | null;
      icon: {
        svg: string | null;
      } | null;
    }> | null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: null;
  } | {
    _key: string;
    _type: "splitForm";
    buttons: null;
    richText: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
      markDefs: null;
    } | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "h4" | "h5" | "h6" | "inline" | "normal";
      listItem?: "bullet" | "check" | "number";
      markDefs: Array<{
        customLink: {
          openInNewTab: boolean | null;
          href: string | null;
        } | null;
        _type: "customLink";
      }> | null;
      level?: number;
      _type: "block";
    }> | null;
    form: {
      _id: string;
      _type: "form";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      label?: string;
      title?: string;
      formId?: string;
      language?: string;
      fields?: Array<{
        _key: string;
      } & FormField>;
      buttonText?: string;
    } | null;
  }> | null;
} | null;
// Variable: getMarketingModalDataQuery
// Query: *[_type == "marketingModal" && isActive][0]{    _id,    title,    description,    defined(form)=>{  form->{    ...,  }}    }
export type GetMarketingModalDataQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  form: {
    _id: string;
    _type: "form";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    label?: string;
    title?: string;
    formId?: string;
    language?: string;
    fields?: Array<{
      _key: string;
    } & FormField>;
    buttonText?: string;
  } | null;
} | null;
// Variable: getOGDataQuery
// Query: *[_id == $id][0]{    _id,    "title":coalesce(ogTitle,title),    "description":coalesce(ogDescription,description),    "image":coalesce(seoImage,image,*[_type =="logo"][0].image).asset->url}
export type GetOGDataQueryResult = {
  _id: string;
  title: null;
  description: null;
  image: null | string;
} | {
  _id: string;
  title: null | string;
  description: null;
  image: null | string;
} | {
  _id: string;
  title: null | string;
  description: null | string;
  image: null | string;
} | {
  _id: string;
  title: string | null;
  description: string | null;
  image: string | null;
} | null;

