name: Deploy sanity studio
on:
  push:
    branches: [main]
    paths:
      - "apps/studio/**"

  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Restore cached Node Modules 💾
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Deploy Studio
        run: cd ./apps/studio && npm run deploy
